apiVersion: apps/v1
kind: Deployment
metadata:
  name: absi-backend-dev
  namespace: dev
  labels:
    app: absi-backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: absi-backend-dev
  template:
    metadata:
      labels:
        app: absi-backend-dev
    spec:
      containers:
        - name: absi-backend-dev
          image: IMAGE_NAME
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: absi-backend-dev