apiVersion: apps/v1
kind: Deployment
metadata:
  name: la7-backend-stg-deployment
  namespace: dev
  labels:
    app: la7-backend-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: la7-backend-stg
  template:
    metadata:
      labels:
        app: la7-backend-stg
    spec:
      containers:
      - name: la7-backend-stg
        image: IMAGE_NAME
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: la7-backend-stg


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: la7-backend-stg-worker-deployment
  namespace: dev
  labels:
    app: la7-backend-stg-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: la7-backend-stg-worker
  template:
    metadata:
      labels:
        app: la7-backend-stg-worker
    spec:
      containers:
      - name: la7-backend-stg-worker
        image: IMAGE_NAME
        command: ["celery", "-A", "Academy_crm", "worker", "--loglevel=info"]
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: la7-backend-stg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: la7-backend-stg-beat-deployment
  namespace: dev
  labels:
    app: la7-backend-stg-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: la7-backend-stg-beat
  template:
    metadata:
      labels:
        app: la7-backend-stg-beat
    spec:
      containers:
      - name: la7-backend-stg-beat
        image: IMAGE_NAME
        command: ["celery", "-A", "Academy_crm", "beat", "--loglevel=info","-S","django"]
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: la7-backend-stg
