apiVersion: apps/v1
kind: Deployment
metadata:
  name: um-in-website-dev
  namespace: dev
  labels:
    app: um-in-website-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: um-in-website-dev
  template:
    metadata:
      labels:
        app: um-in-website-dev
    spec:
      containers:
        - name: um-in-website-dev
          image: IMAGE_NAME
          ports:
            - containerPort: 3000
          # envFrom:
          #   - secretRef:
          #       name: um-in-website-dev
