apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wee_in_backend-dev
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ingressClassName: nginx
  rules:
   - host: wee-dev-api.shelter-technology.com
     http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: wee_in_backend-dev
            port:
              number: 80