apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: um-in-website-prod
  namespace: prod
  annotations:
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/client-max-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ingressClassName: nginx
  rules:
   - host: um-in.com
     http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: um-in-website-prod
            port:
              number: 80
