apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nos-dashboard-react-prod
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ingressClassName: nginx
  rules:
   - host: nos-prod-dashboard.shelter-technology.com
     http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: nos-dashboard-react-prod
            port:
              number: 80