apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: la7-backend-stg
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ingressClassName: nginx
  rules:
   - host: la7-stg-api.shelter-technology.com
     http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: la7-backend-stg
            port:
              number: 80