apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pepsico-dashboard
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ingressClassName: nginx
  rules:
   - host: pepsico-dashboard.shelter-technology.com
     http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: pepsico-dashboard
            port:
              number: 80