apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: dev
  name: nos-tracking-website-stg
spec:
  backendType: secretsManager
  region: eu-west-2
  data:
    - key: NOS-TRACKING-WEBSITE-STG
      name: test
      property: test
