apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: dev
  name: nos-landing-page-safafzco
spec:
  backendType: secretsManager
  region: eu-west-2
  data:
    - key: NOS-LANDING-PAGE-SAFAFZCO
      name: test
      property: test