apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: dev
  name: 5fits-backend-stg
spec:
  backendType: secretsManager
  region: eu-west-2
  data:
    - key: 5FITS-BACKEND-STG
      name: test
      property: test
    - key: 5FITS-BACKEND-STG
      name: DATABASE_URL
      property: DATABASE_URL