apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: dev
  name: wee-in-admin-dashboard-dev
spec:
  backendType: secretsManager
  region: eu-west-2
  data:
    - key: WEE-IN-ADMIN-DASHBOARD-DEV
      name: test
      property: test