apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: dev
  name: la7-backend-stg
spec:
  backendType: secretsManager
  region: eu-west-2
  data:
    - key: LA7-BACKEND-STG
      name: test
      property: test
    - key: LA7-BACKEND-STG
      name: DATABASE_URL
      property: DATABASE_URL
    - key: LA7-BACKEND-STG
      name: PUSHER_ENABLED
      property: PUSHER_ENABLED
    - key: LA7-BACKEND-STG
      name: PUSHER_APP_ID
      property: PUSHER_APP_ID
    - key: LA7-BACKEND-STG
      name: PUSHER_KEY
      property: PUSHER_KEY
    - key: LA7-BACKEND-STG
      name: PUSHER_SECRET
      property: PUSHER_SECRET
    - key: LA7-BACKEND-STG
      name: PUSHER_CLUSTER
      property: PUSHER_CLUSTER
    - key: LA7-BACKEND-STG
      name: PUSHER_BEAM_INSTANCE_ID
      property: PUSHER_BEAM_INSTANCE_ID
    - key: LA7-BACKEND-STG
      name: PUSHER_BEAM_SECRET_KEY
      property: PUSHER_BEAM_SECRET_KEY
    - key: LA7-BACKEND-STG
      name: CELERY_BROKER_URL
      property: CELERY_BROKER_URL
    - key: LA7-BACKEND-STG
      name: CELERY_RESULT_BACKEND
      property: CELERY_RESULT_BACKEND
    - key: LA7-BACKEND-STG
      name: TWILIO_ENABLED
      property: TWILIO_ENABLED
    - key: LA7-BACKEND-STG
      name: TWILIO_ACCOUNT_SID
      property: TWILIO_ACCOUNT_SID
    - key: LA7-BACKEND-STG
      name: TWILIO_AUTH_TOKEN
      property: TWILIO_AUTH_TOKEN
    - key: LA7-BACKEND-STG
      name: TWILIO_FROM_NUMBER
      property: TWILIO_FROM_NUMBER
    - key: LA7-BACKEND-STG
      name: OTP_EXPIRATION_PERIOD_IN_MINUTES
      property: OTP_EXPIRATION_PERIOD_IN_MINUTES
    - key: LA7-BACKEND-STG
      name: S3_ACCESS_KEY
      property: S3_ACCESS_KEY
    - key: LA7-BACKEND-STG
      name: S3_URL
      property: S3_URL
    - key: LA7-BACKEND-STG
      name: S3_ACCESS_SECRET_KEY
      property: S3_ACCESS_SECRET_KEY
    - key: LA7-BACKEND-STG
      name: S3_BUCKET_NAME
      property: S3_BUCKET_NAME
    - key: LA7-BACKEND-STG
      name: S3_REGION
      property: S3_REGION