apiVersion: v1
kind: Service
metadata:
  name: absi-backend-dev
  namespace: dev
  labels:
    service: absi-backend-dev
spec:
  type: ClusterIP
  selector:
    app: absi-backend-dev
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port