apiVersion: v1
kind: Service
metadata:
  name: wee-in-admin-dashboard-dev
  namespace: dev
  labels:
    service: wee-in-admin-dashboard-dev
spec:
  type: ClusterIP
  selector:
    app: wee-in-admin-dashboard-dev
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port