apiVersion: v1
kind: Service
metadata:
  name: fits-frontend-stg
  namespace: dev
  labels:
    service: 5fits-frontend-stg
spec:
  type: ClusterIP
  selector:
    app: 5fits-frontend-stg
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port