apiVersion: v1
kind: Service
metadata:
  name: la7-celery-flower
  namespace: dev
  labels:
    service: la7-celery-flower
spec:
  type: ClusterIP
  selector:
    app: la7-celery-flower
  ports:
  - port: 80         # ClusterIP port
    targetPort: 5555   # Pod port