apiVersion: v1
kind: Service
metadata:
  name: um-in-website-prod
  namespace: prod
  labels:
    service: um-in-website-prod
spec:
  type: ClusterIP
  selector:
    app: um-in-website-prod
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port




