apiVersion: v1
kind: Service
metadata:
  name: wee_in_backend-dev
  namespace: dev
  labels:
    service: wee_in_backend-dev
spec:
  type: ClusterIP
  selector:
    app: wee_in_backend-dev
  ports:
  - port: 80         # ClusterIP port
    targetPort: 8000   # Pod port