apiVersion: v1
kind: Service
metadata:
  name: wee-in-celery-flower
  namespace: dev
  labels:
    service: wee-in-celery-flower
spec:
  type: ClusterIP
  selector:
    app: wee-in-celery-flower
  ports:
  - port: 80         # ClusterIP port
    targetPort: 5555   # Pod port