apiVersion: v1
kind: Service
metadata:
  name: la7-backend-stg
  namespace: dev
  labels:
    service: la7-backend-stg
spec:
  type: ClusterIP
  selector:
    app: la7-backend-stg
  ports:
  - port: 80         # ClusterIP port
    targetPort: 8000   # Pod port