apiVersion: v1
kind: Service
metadata:
  name: absi-backend-prod
  namespace: dev
  labels:
    service: absi-backend-prod
spec:
  type: ClusterIP
  selector:
    app: absi-backend-prod
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port
  sessionAffinity: ClientIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: absi-backend-prod-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: absi-backend-prod
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 3Gi
 

