apiVersion: v1
kind: Service
metadata:
  name: pepsico-dashboard
  namespace: dev
  labels:
    service: pepsico-dashboard
spec:
  type: ClusterIP
  selector:
    app: pepsico-dashboard
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port