apiVersion: v1
kind: Service
metadata:
  name: nos-dashboard-react-stg
  namespace: dev
  labels:
    service: nos-dashboard-react-stg
spec:
  type: ClusterIP
  selector:
    app: nos-dashboard-react-stg
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port