apiVersion: v1
kind: Service
metadata:
  name: nos-backend-service-prod
  namespace: prod
  labels:
    service: nos-backend-service-prod
spec:
  type: ClusterIP
  selector:
    app: nos-backend-service-prod
  ports:
  - port: 80         # ClusterIP port
    targetPort: 8000   # Pod port