apiVersion: v1
kind: Service
metadata:
  name: nos-doc-api
  namespace: dev
  labels:
    service: nos-doc-api
spec:
  type: ClusterIP
  selector:
    app: nos-doc-api
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port