apiVersion: v1
kind: Service
metadata:
  name: nos-landing-page-safafzco
  namespace: dev
  labels:
    service: nos-landing-page-safafzco
spec:
  type: ClusterIP
  selector:
    app: nos-landing-page-safafzco
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port