apiVersion: v1
kind: Service
metadata:
  name: umin-sql-prod
  namespace: prod
  labels:
    service: umin-sql-prod
spec:
  type: ClusterIP
  selector:
    app: umin-sql-prod
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3000   # Pod port




